version: '3'

services:
  api-database-pg:
    container_name: database-pg
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=happydocker
      - POSTGRESQL_DATABASE=findafriend